apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-environment
  namespace: <namespace>
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <user_email>
    privateKeySecretRef:
      name: letsencrypt-pro
    solvers:
    - http01:
        ingress:
          class: nginx
